[package]
name = "gentle-clues"
version = "0.2.1"
entrypoint = "gentle-clue.typ"
authors = ["Jomaway <https://github.com/jomaway>"]
license = "MIT"
description = "A package to simply create and add some admonitions to your documents." 
